### ISSUE TITLE
Buffer.js error with large json

### ISSUE THREAD

**Issue by fabianbaier** [laktak/any-json#6]
I am having a `1.4`GB json file, when trying to use it with `any-json` I get this error:

```
bash-4.3# big.csv > big.json
buffer.js:495
    throw new Error('"toString()" failed');
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.<anonymous> (/usr/lib/node_modules/any-json/bin/any-json:52:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
bash-4.3# ls -alh
```

Looks like we are running into something similar to this: https://stackoverflow.com/questions/42181217/buffer-js-error-in-node-json-too-large

Would switching to https://github.com/dominictarr/JSONStream fix it?

Best,
FB

**Comment by laktak** [comment]
You might get past this step but you'd probably fail when writing the full JSON file.

I'd try to split the csv into smaller parts before sending it to any-json.

**Comment by adamvoss** [comment]
@fabianbaier I think **any-json** would require more modification than just switching the JSON encoding library to prevent your error.  **any-json**'s strength (in my opinion) is that it allows converting a large number of formats using a consistent interface.  Unfortunately, this also means that it does not give you as much control or as optimized of solution.  For a case like yours, you are probably better off using the underlying [**fast-csv**](https://github.com/C2FO/fast-csv) (which does support streaming) library directly (in conjunction with **JSONStream**).

That said, if you write a snippet of code that is able handle your file and can provide it here, I will happily look into integrating it into **any-json**.
